FROM tensorflow/tensorflow:1.4.0-gpu-py3

MAINTAINER Meet P Shah <meetshah1995@gmail.com>

# Expose port 
# 6006 for tensorbard, 
# 443 for visdom
# 8888 for jupyter notebooks
EXPOSE 443 6006 8888

WORKDIR

CMD ["/bin/bash"]